name: MCDocs
main: com.tazzernator.bukkit.mcdocs.MCDocs
version: 11
description: Powerful Documentation and MOTD Plugin. Show information from a file or online using a command that you define.
author: Tazzernator (Andrew Tajsic)
website: http://dev.bukkit.org/server-mods/mcdocs/
commands:
  mcdocs:
    description: Reloads MCDocs
    usage: /mcdocs -reload  |  Reloads MCDocs.
    permission: mcdocs.reload